### ISSUE TITLE
build.ps1 should set version metadata

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGet.Jobs#122]
NuGet.Jobs/build.ps1
* Should set version metadata in AssemblyInfo.cs, same as done in NuGetGallery
* Should pack from nuspec instead of csproj for each job

*Note that NuGet.Services.Metadata/build.ps1 also needs updating.*

**Comment by joelverhagen** [comment]
Issue moved to [NuGet/NuGetGallery #4838](https://github.com/NuGet/NuGetGallery/issues/4838) via [**ZenHub**](https://www.zenhub.com/)
